# -*- coding: utf-8 -*-
"""image_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FN0Dk3n6WdP_WZuZ75lwHXcDGYUVccK
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Load the MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Preprocess the data
X_train, X_test = X_train / 255.0, X_test / 255.0  # Normalize pixel values to [0, 1]
y_train = to_categorical(y_train, 10)  # One-hot encode the labels for 10 classes
y_test = to_categorical(y_test, 10)

# Build the model
model = Sequential([
    Flatten(input_shape=(28, 28)),   # Flatten the 28x28 images
    Dense(128, activation='relu'),   # Fully connected layer with 128 neurons
    Dense(64, activation='relu'),    # Another layer with 64 neurons
    Dense(10, activation='softmax')  # Output layer for 10 classes
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=32, validation_split=0.2)

# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_accuracy:.2f}")